spring:
  application:
    name: exercise-tracker
  datasource:
    url: jdbc:postgresql://localhost:5432/exercise_tracker
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
server:
  error:
    include-binding-errors: always